"""create appointments table

Revision ID: 2778e0199497
Revises: 801283605dc1
Create Date: 2026-06-20 22:04:47.542686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2778e0199497'
down_revision: Union[str, Sequence[str], None] = '801283605dc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_name', sa.String(length=100), nullable=False),
    sa.Column('patient_email', sa.String(length=255), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('slot_time', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_date', 'slot_time', name='uq_appointment_slot')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointments')
    # ### end Alembic commands ###
