"""add file_hash to clinic_docs

Revision ID: 801283605dc1
Revises: eb28801e5264
Create Date: 2026-06-19 17:30:06.264291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '801283605dc1'
down_revision: Union[str, Sequence[str], None] = 'eb28801e5264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinic_docs', sa.Column('file_hash', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_clinic_docs_file_hash'), 'clinic_docs', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinic_docs_file_hash'), table_name='clinic_docs')
    op.drop_column('clinic_docs', 'file_hash')
    # ### end Alembic commands ###
